### PR TITLE
Create PermissionsDependenciesDataPullOut and PermissionsOperatorDataPullOut

### PR DESCRIPTION
**Pull request by Domenico-Pirozzi**

### CODE REVIEW

**Comment by gregoriozoppi** [comment]
add missing classes

**Review by STS-SW — APPROVED** [review]

**Review by STS-SW — APPROVED** [review]
.

**Comment by gregoriozoppi** [comment]
Remove OperatorPermission  datapullout (it was done with query on db)
Implement generic db feeding

**Comment by gregoriozoppi** [comment]
.

**Comment by gregoriozoppi** [comment]
reopen

**Review by STS-SW — APPROVED** [review]

**Review by STS-SW — APPROVED** [review]
Ok

**Review by Stefano-Sarina — APPROVED** [review]

**Pull request merged**
